include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - prefer_spread_collections

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_pub_dependencies: false
    unused_element: false
  exclude:
    ../*.freezed.dart
    ../*.gr.dart
